#!/bin/bash
# Copyright (C) 2009 Simone Karin Lehmann, simone at lisanet dot de 
# set-fontsize 1.0
# This script only exists on Leopard. It calculates the font size GIMP
# should use for its menus. The value is only set, if the user has not
# set any other gtk-font-name value in "~/Library/Application Support/Gimp/gtkrc"
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
GTKRC="$HOME/Library/Application Support/Gimp/gtkrc"

# Default 96 since 10.5.7
DPI=96
FSIZE=`dc -e "1k 72 100 * $DPI / 13 * 5 + 100 / p"`

if [ ! -e "$GTKRC" ]; then
  mkdir -p "$HOME/Library/Application Support/Gimp"
  cat << EOF > "$GTKRC"
# GIMP gtkrc
# 
# This is your personal gtkrc file.  Any variable defined in this file takes
# precedence over the value defined in the system-wide gtkrc:
# 
# This is the formula to calculate the font size for GIMP's menus
# font_size = (72 / X11_dpi) * 13
#
# X11_dpi is the dpi value your X11 is set to. Since 10.5.7 this is by default: 96 dpi
# to change the dpi setting open Terminal.app and type
#     defaults write org.x.X11 dpi -int <new-dpi-value>
# BTW, the default font size for Mac OS X is 13 pixel.
#
# X11 set to 96 dpi
# gtk-font-name = "Lucida Grande 9.8"
# X11 set to 113 dpi 
# gtk-font-name = "Lucida Grande 8.3"
#
EOF
fi

OPTSET=
grep -q "^ *gtk-font-name" "$GTKRC" && OPTSET=true
if [ "$OPTSET" != "true" ]; then
  echo "" >> "$GTKRC"
  echo "# default font size" >> "$GTKRC"
  echo "gtk-font-name = \"Lucida Grande $FSIZE\"" >> "$GTKRC"
fi

OPTSET=
grep -q "^ *gtk-print-preview-command" "$GTKRC" && OPTSET=true
if [ "$OPTSET" != "true" ]; then
  echo >> "$GTKRC"
  echo "# use OS X default pdf-viewer for print preview" >> "$GTKRC"
  echo "gtk-print-preview-command=\"open %f\"" >> "$GTKRC"
fi
