#!/bin/sh

export PATH="${PATH}:/usr/bin:/bin:/usr/local/bin"
export GIMP2_DIRECTORY="Library/Application Support/Gimp"

DIR=`dirname "$0"`
source "$DIR/gimp-dbus"
set_dbus_session_bus_address

exec gimp-2.8 "$@"
