#!/bin/bash
# Copyright (C) 2009 Simone Karin Lehmann, simone at lisanet dot de 
# help-locale 1.2.2
# update help-locale to use the language, hte user has set via System Preferences
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
GIMPRC="$HOME/Library/Application Support/Gimp/gimprc"

if [ ! -e "$GIMPRC" ]; then
  mkdir -p "$HOME/Library/Application Support/Gimp"
  cat << EOF > "$GIMPRC"
# GIMP gimprc
# 
# This is your personal gimprc file.  Any variable defined in this file takes
# precedence over the value defined in the system-wide gimprc:
# /tmp/skl/Gimp.app/Contents/Resources/etc/gimp/2.0/gimprc
# Most values can be set within GIMP by changing some options in the
# Preferences dialog.

(help-locales "")

# end of gimprc
EOF
fi

# get langauges set by System Preferences
LANGS=`defaults read -g AppleLanguages | tr -d "() \n\"" | sed "s/-/_/g;s/Hans/CN/;s/Hant/TW/;s/,/:/g"`

# set help language
OPTSET=
grep -q help-locales "$GIMPRC" && OPTSET=true
if [ "$OPTSET" != "true" ]; then
  sed -i "" -e "s/# end of g.*//" "$GIMPRC"
  echo \(help-locales \"$LANGS\"\) >> "$GIMPRC"
  echo "# end of gimprc" >> "$GIMPRC"
fi

# update language sort order
OPTSET=
grep -q "$LANGS" "$GIMPRC" && OPTSET=true
if [ "$OPTSET" != "true" ]; then
  sed -i "" -e "s/help-locales \".*\"/help-locales \"$LANGS\"/" "$GIMPRC"
fi
