#!/bin/sh
#
# (c) 2008, Simone Karin Lehmann, simone at lisanet dot de
# GPL version 2 or later
# script 1.3 Leo

DIR=`dirname "$0"`

# update fonts cache from 2.6.1 to 2.6.2
"$DIR/update-fc-cache"

# setup gimp user directories
"$DIR/setup-gimpdir"

# setup help, for more information see bin/help-locale
"$DIR/help-locale"

# deal with gtkrc in "~/Library/Application Support/Gimp"
"$DIR/fix_gtkrc"

exec "$DIR/gimp-remote" "$@"
