#!/bin/bash
# Copyright (C) 2008 Simone Karin Lehmann, simone at lisanet dot de 
# update-fc-cache
# In the application bundle of 2.6.1 the fonts cache dir not stored in teh
# wrong directory. This script simply deletes this. Gimp will recreate it on the fly.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
if [ -d "$HOME/Library/Application Support/cache/fonts" ]; then
	  rm -rf "$HOME/Library/Application Support/cache/fonts"
	  rm -f "$HOME/Library/Application Support/cache/.DS_Store"
	  rmdir "$HOME/Library/Application Support/cache"
fi
