#!/bin/sh
#
# (c) 2008, Simone Karin Lehmann, simone at lisanet dot de
# GPL version 2 or later
# script 1.3 Leo

DIR=`dirname "$0"`
cd "$DIR/../.."
APPDIR=`pwd`
cd - > /dev/null
# edit the next line to match version file
VERSION=_VERSION_
LNDIR=/tmp/skl/Gimp.app
if [ ! -e "$LNDIR/Contents/Resources/v$VERSION" ]; then
	rm -f "$LNDIR"
	mkdir -p /tmp/skl
	chmod a+w /tmp/skl
	ln -s "$APPDIR" "$LNDIR"
fi

CWD="/tmp/skl/Gimp.app/Contents/Resources"

# update fonts cache from 2.6.1 to 2.6.2
"$CWD/bin/update-fc-cache"
# setup gimp user directories
"$CWD/bin/setup-gimpdir"
# setup help, for more information see bin/help-locale
rm -f /tmp/skl/Gimphelp
ln -s "$DIR/share/gimp/2.0/nohelp" /tmp/skl/Gimphelp
"$CWD/bin/help-locale"
# this only exists on Leopard, set font size
if [ -e "$CWD/bin/set-fontsize" ]; then
  "$CWD/bin/set-fontsize"
fi

cd ~/ > /dev/null
exec "$CWD/bin/gimp" "$@"
